Sprint 19
PetrovaOla/PlaylistMaker pull request #13
Opened 2024-04-27 15:06 UTC by PetrovaOla

2024-04-28 02:41 UTC, DmitrijEgorow requested changes

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/build.gradle.kts
> +    implementation(libs.androidx.navigation.fragment.ktx)
Круто

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/java/petrova/ola/playlistmaker/play/ui/PlayViewModel.kt
> +        "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview112/v4/ac/c7/d1/acc7d13f-6634-495f-caf6-491eccb505e8/mzaf_4002676889906514534.plus.aac.p.m4a"
Зачем?

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/java/petrova/ola/playlistmaker/play/ui/PlayViewModel.kt
> +//        playerInteractor.setDataSource(url)
Лучше не вливать закомментированный код в мастер

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/java/petrova/ola/playlistmaker/play/ui/PlayViewModel.kt
> +//        SimpleDateFormat("mm:ss", Locale.getDefault()).format(mediaPlayer.currentPosition) ?: "00:00"
Аналогично

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/java/petrova/ola/playlistmaker/player/ui/PlayerActivity.kt
> +            else -> intent.getParcelableExtra(SearchFragment.EXTRAS_KEY)!!
Аккуратнее с этим оператором

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/java/petrova/ola/playlistmaker/search/data/NetworkClient.kt
> +    suspend fun doRequestSuspend(dto: Any): Response
Может, не Any, а что-то более конкретное?

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/java/petrova/ola/playlistmaker/search/domain/model/Track.kt
> +import android.os.Parcelable
domain слой зависит от Android фреймворка

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/java/petrova/ola/playlistmaker/search/ui/SearchViewModel.kt
>      private val application: Application,
Зачем ViewModel нужен именно Application?

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_play.xml
> +            android:id="@+id/guideline2"
можно поменять идентификатор

2024-04-28 02:41 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_play.xml
> +            android:id="@+id/button_like"
Разные стили именования идентификаторов

2024-04-28 02:42 UTC, DmitrijEgorow commented
На устройствах с увеличенным размером шрифта такой визуальный артефакт

![Screenshot_20240428_092407](https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/616951f7-6d48-453b-849f-5bbccb3ff14e)

2024-04-28 02:45 UTC, DmitrijEgorow commented
- [ ] Два разных состояния отображаются одновременно
- [ ] Поиск работает не всегда, показывается список треков, который не соответствует последнему запросу
- [ ] На устройствах с увеличенным размером шрифта происходит обрезка текста по вертикали, подробнее про вёрстку для таких случаев можно почитать https://support.google.com/accessibility/android/answer/12159181


https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/af88ae8d-9505-468c-b354-bd10627cfead

2024-04-28 02:47 UTC, DmitrijEgorow commented
Какой из двух статусов правильный?

https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/8efce7ed-844f-4963-8ebc-1622cd639e84

2024-05-01 10:03 UTC, DmitrijEgorow commented
Два оттенка белого выглядят не очень красиво
![Screenshot_20240501_164023](https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/6dd524bf-5ea4-4b80-9f22-31b1c1be06dc)

2024-05-01 10:06 UTC, DmitrijEgorow commented
Избранные треки и Плейлисты имеют странную заливку иным оттенком белого по сравнению с основным фоном

https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/f1d80dad-9581-472a-8548-63213e23008b

Этот запрос должен был выдать какие-то результаты
А вот и причина:
<img width="1020" alt="Screenshot 2024-05-01 at 16 34 48" src="https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/23c4dfa6-cc98-4b5d-8536-6f44f5a38f5a">

2024-05-02 12:54 UTC, PetrovaOla commented
> Избранные треки и Плейлисты имеют странную заливку иным оттенком белого по сравнению с основным фоном
> 
>  Screen_recording_20240501_163809.mp4 
> Этот запрос должен был выдать какие-то результаты (заглушка "Ничего не нашлось" не должна вообще показываться в таком случае) А вот и причина: <img alt="Скриншот 2024-05-01 в 16 34 48" width="1020" src="https://private-user-images.githubusercontent.com/36837067/327099626-23c4dfa6-cc98-4b5d-8536-6f44f5a38f5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTM3ODEsIm5iZiI6MTcxNDY1MzQ4MSwicGF0aCI6Ii8zNjgzNzA2Ny8zMjcwOTk2MjYtMjNjNGRmYTYtY2M5OC00YjVkLTg1MzYtNmY0NGY1YTM4ZjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEyMzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTBlOWZhNzQzNjY2OTMwMDM1NDRlYWU1OWJlYWViOGU5MDdiZjA2NGRiYmY3NmMwYjZmYmQzZmY4MzU4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._q1IGK78acbcl9PWWlSZ9xBsErTR8o2a1p7ARnllfvk">
Не могу повторить последний коментарий:
https://github.com/PetrovaOla/PlaylistMaker/assets/59420509/b8537a78-2878-4ad5-97fc-6deaad59ac18

2024-05-03 16:02 UTC, DmitrijEgorow commented
> > Не могу повторить последний коментарий:
> > https://github.com/PetrovaOla/PlaylistMaker/assets/59420509/b8537a78-2878-4ad5-97fc-6deaad59ac18
Нужно нажать на кнопку Done на клавиатуре

2024-05-03 16:02 UTC, DmitrijEgorow commented
> > > Не могу повторить последний коментарий:
> > > https://github.com/PetrovaOla/PlaylistMaker/assets/59420509/b8537a78-2878-4ad5-97fc-6deaad59ac18
Нужно нажать на кнопку Done на клавиатуре

2024-05-03 16:14 UTC, DmitrijEgorow commented
https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/3c4c3d0f-de1d-4214-ab1b-2c1f9076c334

2024-05-03 16:15 UTC, DmitrijEgorow commented
Тёмная тема приложения

![Screenshot_20240503_230455](https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/ba7a9484-127e-4528-86ab-4d95bb23d90e)
![Screenshot_20240503_230445](https://github.com/PetrovaOla/PlaylistMaker/assets/36837067/27eb0ac4-301b-4951-9b74-6fc626aa32f0)

2024-05-04 08:55 UTC, merged